#!/usr/bin/env python3
"""spec_parity.py — SPEC ↔ GENERIC INSTANCE parity check (the generation test's spec driver).

For every entry of AGENT_SPEC.md, resolve the artifacts its fields NAME (backticked path-like
tokens) against a freshly generated instance. A spec entry that names a file the instance does not
ship is a FAILURE — so declaring a capability in the spec forces the template to ship it, and
shipping a file the spec never names is caught by the spec's own drift check instead.

Resolution rules (deliberately explicit, never silent):
  * a token is resolved if it exists in the instance (root-relative or by basename anywhere), or in
    the generator root (generator-side artifacts such as test_instance.sh);
  * `{a,b}` brace composites are split and each member must resolve;
  * tokens containing a placeholder (`<...>`) are skipped: they are the use-case layer;
  * a documented ALLOWLIST covers artifacts that legitimately do not ship at generation time
    (Phase-3 data-doctrine files, optional integrations).

Usage:
  python3 spec_parity.py --instance <dir> [--spec <AGENT_SPEC.md>] [--generator <dir>] [--json]
Exit 0 = every referenced artifact resolves ; 1 = at least one does not (listed).
"""
import argparse, json, os, re, sys

FIELD_TOKENS = re.compile(r'`([^`]+)`')
EXT = re.compile(r'\.(sh|py|md|json|jsonl|js|html|yml|yaml)$')
PLACEHOLDER = re.compile(r'<[^>]*>')
RANGE = re.compile(r'^\S+\.\.\S+$')
FLAGISH = re.compile(r'--')          # CLI flag chain (--column/--group-by), not a path
GLOBBY = re.compile(r'[*?]')          # glob pattern, not a shipped file

# Tokens that are deliberately NOT required to exist as shipped files. Each entry states WHY.
ALLOWLIST = {
    # use-case layer / grounding (Phase 3-6)
    "API_REFERENCE.md": "Phase-3 data doctrine (written when the instance is grounded)",
    "api_endpoints.json": "Phase-3 data doctrine (endpoint map, written at grounding)",
    "telegram_bot.js": "G4 optional — no channel wired (reported na by core_check)",
    # runtime artifacts: produced by a shipped mechanism, never part of the skeleton
    "verification.json": "runtime sidecar written by run_calc.py at delivery time",
    "looptrace.json": "runtime 8-step loop trace written by loop.sh / guard_loop.sh",
    "index.html": "runtime catalogue page generated by update_deliverables_index.py",
    "BRIEF.md": "runtime boot digest generated by state/memory/make_brief.sh",
    "journal_conformite.jsonl": "runtime gate journal, created on the first gated delivery",
}


def is_file_ref(tok):
    """True only for tokens that should name a file/dir on disk."""
    if PLACEHOLDER.search(tok) or RANGE.match(tok):
        return False
    if FLAGISH.search(tok) or GLOBBY.search(tok):
        return False
    if tok.startswith("/"):            # HTTP route (/monitor, /spec), not a filesystem path
        return False
    if EXT.search(tok):                # a real file name
        return True
    return tok.endswith("/")           # a directory reference (Machinery/cockpit/observability/)


def index(root):
    """basename -> [relpaths] over a tree."""
    idx = {}
    for dp, _, fs in os.walk(root):
        for f in fs:
            idx.setdefault(f, []).append(os.path.relpath(os.path.join(dp, f), root))
    return idx


def generator_index(root):
    """Generator-SIDE artifacts only: the generator's own top-level files.

    Deliberately NOT recursive — the generator contains `instance-template/`, and indexing that
    would let a file missing from the GENERATED instance still 'resolve' against the template,
    making the parity check unable to fail. The instance index must prove what the instance ships.
    """
    idx = {}
    try:
        for f in os.listdir(root):
            p = os.path.join(root, f)
            if os.path.isfile(p):
                idx.setdefault(f, []).append(f)
    except OSError:
        pass
    return idx


def load_entries(spec_path):
    """Parse the spec into {id: {'group','title','fields'}} the same way spec_gen.sh does."""
    txt = open(spec_path, encoding="utf8").read()
    group_re = re.compile(r'^## ([A-I])\. (.*?) \((\d+)\)\s*$')
    entry_re = re.compile(r'^### ([A-I])(\d+)([a-z]?)\s*—?\s*(.*)$')
    fields = ["Purpose", "Mechanism", "I/O", "Composes"]
    entries, curg, cur, blocks = {}, None, None, []
    body = []
    for ln in txt.splitlines():
        gm = group_re.match(ln)
        if gm:
            curg = gm.group(1); continue
        em = entry_re.match(ln)
        if em and curg:
            if cur is not None:
                blocks.append((cur, body))
            cur = "%s%s%s" % (em.group(1), em.group(2), em.group(3))
            entries[cur] = {"id": cur, "group": curg, "title": em.group(4).strip(), "fields": {}}
            body = []; continue
        if cur is not None:
            body.append(ln)
    if cur is not None:
        blocks.append((cur, body))
    for eid, b in blocks:
        # A field starts at '- **Field:**' and CONTINUES on following lines until the next
        # '- **' (fields are wrapped across lines throughout the spec — reading only the first
        # line silently drops the artifacts named on continuation lines).
        cur_f, buf = None, {}
        for ln in b:
            m = re.match(r'^- \*\*(Purpose|Mechanism|I/O|Composes):\*\* ?(.*)$', ln)
            if m:
                cur_f = m.group(1)
                buf[cur_f] = m.group(2).strip()
            elif cur_f and ln.strip():
                buf[cur_f] = (buf[cur_f] + " " + ln.strip()).strip()
        entries[eid]["fields"] = buf
    return entries


def tokens_of(entry):
    toks = set()
    for v in entry.get("fields", {}).values():
        for m in FIELD_TOKENS.findall(v):
            t = m.split()[0].strip().strip('.,;:')
            if is_file_ref(t):
                toks.add(t)
    return toks


def resolves(tok, inst, inst_idx, gen, gen_idx):
    parts = [tok]
    if "{" in tok and "}" in tok:                      # tests/{a.sh,b.py}
        pre, rest = tok.split("{", 1)
        inner, post = rest.split("}", 1)
        parts = [pre + p.strip() + post for p in inner.split(",") if p.strip()]
    for p in parts:
        if os.path.exists(os.path.join(inst, p)) or os.path.exists(os.path.join(gen, p)):
            continue
        base = os.path.basename(p.rstrip("/"))
        if base in inst_idx or base in gen_idx:
            continue
        return False, p
    return True, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--instance", required=True)
    ap.add_argument("--spec", default=None)
    ap.add_argument("--generator", default=os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    gen = os.path.abspath(a.generator)
    inst = os.path.abspath(a.instance)
    spec = a.spec or os.path.join(gen, "AGENT_SPEC.md")
    for p, what in ((inst, "instance"), (spec, "spec")):
        if not os.path.exists(p):
            print(f"ERR: {what} not found: {p}", file=sys.stderr); return 2

    entries = load_entries(spec)
    inst_idx, gen_idx = index(inst), generator_index(gen)

    checked = resolved = skipped = allowed = 0
    missing = []           # (entry_id, token)
    for eid in sorted(entries):
        for tok in sorted(tokens_of(entries[eid])):
            if tok in ALLOWLIST:
                allowed += 1; continue
            checked += 1
            ok, bad = resolves(tok, inst, inst_idx, gen, gen_idx)
            if ok:
                resolved += 1
            else:
                missing.append((eid, bad))

    out = {"spec": os.path.relpath(spec, gen), "instance": inst,
           "entries": len(entries), "checked": checked, "resolved": resolved,
           "placeholders_skipped": skipped, "allowlisted": allowed,
           "missing": [{"entry": e, "token": t} for e, t in missing],
           "ok": not missing}
    if a.json:
        print(json.dumps(out, ensure_ascii=False, indent=2))
    else:
        print(f"spec-parity: {resolved}/{checked} referenced artifacts resolve "
              f"({len(entries)} entries; {skipped} placeholder, {allowed} allowlisted)")
        for e, t in missing:
            print(f"  MISSING  {e:<5} -> {t}")
    return 0 if not missing else 1


if __name__ == "__main__":
    sys.exit(main())
