#!/bin/bash
# make_brief.sh — boot digest generator (generic standalone instance).
# Renders state/memory/BRIEF.md from the ledger: active labels, doctrine rows,
# and the last 10 beliefs by NUMERIC id (the Forget list sits after the Ledger table).
# Idempotent: rerun after every ledger write. Reads ONLY this instance's own ledger.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"           # <INSTANCE>/state/memory
LEDGER="$HERE/beliefs.md"
BRIEF="$HERE/BRIEF.md"

[ -r "$LEDGER" ] || { echo "FAIL: ledger not readable: $LEDGER"; exit 1; }

max_id() {  # largest numeric B-xxx id in the ID COLUMN only (not mentions in content)
  grep '^\| B-[0-9]' "$LEDGER" | sed -E 's/^\| B-([0-9]+).*/\1/' | sort -n | tail -1
}

MAXID="$(max_id)"
[ -n "$MAXID" ] || { echo "FAIL: no B-xxx ids found in ledger"; exit 1; }

{
  echo "# Boot digest — memory (generated)"
  echo
  echo "> AUTO-GENERATED by \`make_brief.sh\` — a boot AID, not the memory."
  echo "> FIRST ACTION of every session: read the full ledger \`state/memory/beliefs.md\`."
  echo "> Ledger max id: **B-$MAXID** (boot stamp target). Generated: $(date '+%Y-%m-%d %H:%M')."
  echo "> BOOT STAMP: **B-$MAXID** = max courant (AUTO-VALIDÉ à la génération)."
  echo "> À CHAQUE BOOT : lis le ledger 'beliefs.md' EN ENTIER (le digest est un aide-mémoire, pas la mémoire)."
  echo
  echo "## Active labels"
  awk -F'|' '/^\| L-[0-9]/ {gsub(/ /,"",$2); gsub(/ /,"",$6); if (tolower($6)=="active") printf "- %s %s\n", $2, $3}' "$LEDGER" | sed 's/^ *//;s/  */ /g' | head -30
  echo
  echo "## Doctrine (obey first)"
  awk -F'|' '/^\| B-[0-9]/ {t=tolower($3); s=tolower($11); if (t ~ /doctrine/ && s !~ /superseded|discarded/) printf "- %s %s\n", $2, substr($4,1,110)}' "$LEDGER" | sed 's/^ *//;s/  */ /g'
  echo
  echo "## Références chiffrées (faits) — à RE-DÉRIVER, jamais une source"
  echo "> Instantanés (base + date + source). Pour tout chiffre livré : re-dériver live + vérifier indépendamment."
  [ -r "$HERE/facts.md" ] && awk -F'|' '/^\| F-[0-9]/ {printf "- %s %s (base %s, %s)\n", $2, substr($4,1,34), $5, $8}' "$HERE/facts.md"
  echo
  echo "## Last 10 beliefs (newest last)"
  grep '^\| B-[0-9]' "$LEDGER" | awk -F'|' '{id=$2; gsub(/ /,"",id); n=id; sub(/^B-0*/,"",n); print n+0 "\t" id "\t" substr($4,1,100)}' | sort -n | uniq | tail -10 | cut -f2,3 | awk -F'\t' '{printf "- %s %s\n", $1, $2}'
  echo
} > "$BRIEF"

iconv -c -f UTF-8 -t UTF-8 "$BRIEF" > "$BRIEF.tmp" && mv "$BRIEF.tmp" "$BRIEF"

# --- regenerate the instance's own AGENTS.md pointer (embedded digest) -------
CORE="$(cd "$HERE/../.." && pwd)"
{
  echo "# {{INSTANCE_NAME}} — workspace pointer (standalone SNemo instance)"
  echo
  echo "> This is a **standalone instance**: its OWN brain, its OWN memory."
  echo "> **Do NOT connect to any shared brain** (~/.dsh/core-path). Identity comes from the mode."
  echo "> **FIRST ACTION: read the full ledger \`state/memory/beliefs.md\` — the digest below"
  echo "> is a boot aid, NOT the memory.** Then follow \`AGENT_CORE.md\` (this root) read-first list."
  echo
  cat "$BRIEF"
} > "$CORE/AGENTS.md"

echo "BRIEF.md written (ledger max B-$MAXID); core-root AGENTS.md pointer refreshed"
